spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_study
    username: root
    password: mysql789

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      # shoq_sql: true
      format_sql: true
