spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_study
    username: root
    password: mysql789

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      # shoq_sql: true
      format_sql: true
app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app-jwt-expiration-milliseconds: 604800000